class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'hi': {
      'chooseLanguageTitle': 'Choose Your\nLanguage',
      'chooseLanguageSubtitle': 'अपनी आध्यात्मिक यात्रा के लिए पसंदीदा भाषा चुनें।',
      'getStarted': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'hariPath': 'Hari Path',
      'welcomeToHariPath': 'Welcome to Hari Path',
      'welcomeDesc1': 'Begin Your Spiritual Journey. Immerse yourself in a guided path of devotion, mindfulness, and inner peace.',
      'naamJaapTitle': 'Daily Naam Jaap',
      'naamJaapDesc': 'काउंटर और माला के साथ अपने दैनिक नाम जप का अभ्यास करें और अपनी प्रगति ट्रैक करें।',
      'amritVachanTitle': 'Amrit Vachan & Satsang',
      'amritVachanDesc': 'प्रतिदिन दिव्य उपदेश, आध्यात्मिक विचार और संतों के वचनों से अपने जीवन को संवारें।',
      'loginTitle': 'लॉगिन करें',
      'phoneHint': 'मोबाइल नंबर दर्ज करें',
      'sendOtp': 'ओटीपी भेजें',
    },
    'en': {
      'chooseLanguageTitle': 'Choose Your\nLanguage',
      'chooseLanguageSubtitle': 'Select the language you prefer for your spiritual journey.',
      'getStarted': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'hariPath': 'Hari Path',
      'welcomeToHariPath': 'Welcome to Hari Path',
      'welcomeDesc1': 'Begin Your Spiritual Journey. Immerse yourself in a guided path of devotion, mindfulness, and inner peace.',
      'naamJaapTitle': 'Daily Naam Jaap',
      'naamJaapDesc': 'Chant holy names daily with digital jaap counter, track streaks, and elevate your spiritual energy.',
      'amritVachanTitle': 'Amrit Vachan & Satsang',
      'amritVachanDesc': 'Discover sacred quotes, daily wisdom, uplifting discourses, and holy teachings.',
      'loginTitle': 'Login to Your Account',
      'phoneHint': 'Enter Mobile Number',
      'sendOtp': 'Send OTP',
    },
    'mr': {
      'chooseLanguageTitle': 'Choose Your\nLanguage',
      'chooseLanguageSubtitle': 'आपल्या आध्यात्मिक प्रवासासाठी पसंतीची भाषा निवडा.',
      'getStarted': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'hariPath': 'Hari Path',
      'welcomeToHariPath': 'Welcome to Hari Path',
      'welcomeDesc1': 'Begin Your Spiritual Journey. Immerse yourself in a guided path of devotion, mindfulness, and inner peace.',
      'naamJaapTitle': 'Daily Naam Jaap',
      'naamJaapDesc': 'डिजिटल जपमाळेसह दररोज नामजप करा आणि आपली प्रगती ट्रॅक करा.',
      'amritVachanTitle': 'Amrit Vachan & Satsang',
      'amritVachanDesc': 'दररोज अमृत वचन, प्रवचने आणि आध्यात्मिक विचारांचा लाभ घ्या.',
      'loginTitle': 'लॉगिन करा',
      'phoneHint': 'मोबाईल नंबर प्रविष्ट करा',
      'sendOtp': 'ओटीपी पाठवा',
    },
    'gu': {
      'chooseLanguageTitle': 'Choose Your\nLanguage',
      'chooseLanguageSubtitle': 'તમારી આધ્યાત્મિક યાત્રા માટે પસંદગીની ભાષા પસંદ કરો.',
      'getStarted': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'hariPath': 'Hari Path',
      'welcomeToHariPath': 'Welcome to Hari Path',
      'welcomeDesc1': 'Begin Your Spiritual Journey. Immerse yourself in a guided path of devotion, mindfulness, and inner peace.',
      'naamJaapTitle': 'Daily Naam Jaap',
      'naamJaapDesc': 'ડિજિટલ માળા સાથે દરરોજ નામ જાપ કરો અને તમારી પ્રગતિ જુઓ.',
      'amritVachanTitle': 'Amrit Vachan & Satsang',
      'amritVachanDesc': 'રોજિંદા અમૃત વચન, સત્સંગ અને પવિત્ર જ્ઞાન મેળવો.',
      'loginTitle': 'લોગિન કરો',
      'phoneHint': 'મોબાઇલ નંબર દાખલ કરો',
      'sendOtp': 'ઓટીપી મોકલો',
    },
    'ta': {
      'chooseLanguageTitle': 'Choose Your\nLanguage',
      'chooseLanguageSubtitle': 'உங்கள் ஆன்மீக பயணத்திற்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
      'getStarted': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'hariPath': 'Hari Path',
      'welcomeToHariPath': 'Welcome to Hari Path',
      'welcomeDesc1': 'Begin Your Spiritual Journey. Immerse yourself in a guided path of devotion, mindfulness, and inner peace.',
      'naamJaapTitle': 'Daily Naam Jaap',
      'naamJaapDesc': 'டிஜிட்டல் ஜெபமாலையுடன் தினசரி நாம ஜெபம் செய்து ஆன்மீக அமைதி பெறுங்கள்.',
      'amritVachanTitle': 'Amrit Vachan & Satsang',
      'amritVachanDesc': 'தினசரி ஆன்மீக சிந்தனைகள் மற்றும் வழிகாட்டுதல்களைப் பெறுங்கள்.',
      'loginTitle': 'உள்நுழைக',
      'phoneHint': 'கைபேசி எண் உள்ளிடவும்',
      'sendOtp': 'OTP அனுப்பவும்',
    },
    'te': {
      'chooseLanguageTitle': 'Choose Your\nLanguage',
      'chooseLanguageSubtitle': 'మీ ఆధ్యాత్మిక ప్రయాణానికి ప్రాధాన్యత గల భాషను ఎంచుకోండి.',
      'getStarted': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'hariPath': 'Hari Path',
      'welcomeToHariPath': 'Welcome to Hari Path',
      'welcomeDesc1': 'Begin Your Spiritual Journey. Immerse yourself in a guided path of devotion, mindfulness, and inner peace.',
      'naamJaapTitle': 'Daily Naam Jaap',
      'naamJaapDesc': 'డిజిటల్ జపమాలతో ప్రతిరోజూ నామ జపం చేయండి మరియు ప్రశాంతతను పొందండి.',
      'amritVachanTitle': 'Amrit Vachan & Satsang',
      'amritVachanDesc': 'ప్రతిరోజూ దివ్య వచనాలు మరియు ఆధ్యాత్మిక ప్రవచనాలను వినండి.',
      'loginTitle': 'లాగిన్ చేయండి',
      'phoneHint': 'మొబైల్ సంఖ్య నమోదు చేయండి',
      'sendOtp': 'OTP పంపండి',
    },
  };

  static String get(String key, {String lang = 'hi'}) {
    return _localizedValues[lang]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
